### ISSUE TITLE
GCP: Listings show 0 pages

### ISSUE THREAD

**Issue by major** [redhatcloudx/cloud-image-directory-frontend#55]
On the GCP listing page, it shows "0 - 0 of 0" for the page count.

**Comment by FKolwa** [comment]
Taken a look at it. That issue is caused by the pages file in the S3 bucket. our pages start with the name "0" which means that the content of the pages file is actually completely accurate when it says 
`{"first": 0, "last": 0, "entries": 50}` 
But as we parse this file in front-end to get the number of entries / pages we calculate the last page * number of entries which obviously results in 0 entries and 0 pages :p
